import { FOLLOWUP_PRIORITY, FOLLOWUP_REASON, FOLLOWUP_SOURCE } from './types.js'
import { FOLLOWUP_REASON_ACTIONS, FOLLOWUP_REASON_LABELS } from './statuses.js'

export const FOLLOWUP_REASON_META = Object.freeze({
  [FOLLOWUP_REASON.NEVER_OPENED]: {
    reason: FOLLOWUP_REASON.NEVER_OPENED,
    sourceType: FOLLOWUP_SOURCE.PROPOSAL,
    priority: FOLLOWUP_PRIORITY.MEDIUM,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.NEVER_OPENED],
  },
  [FOLLOWUP_REASON.AWAITING_RESPONSE]: {
    reason: FOLLOWUP_REASON.AWAITING_RESPONSE,
    sourceType: FOLLOWUP_SOURCE.PORTAL,
    priority: FOLLOWUP_PRIORITY.MEDIUM,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.AWAITING_RESPONSE],
  },
  [FOLLOWUP_REASON.CLIENT_INTERACTION]: {
    reason: FOLLOWUP_REASON.CLIENT_INTERACTION,
    sourceType: FOLLOWUP_SOURCE.INTERACTION,
    priority: FOLLOWUP_PRIORITY.HIGH,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.CLIENT_INTERACTION],
  },
  [FOLLOWUP_REASON.CHANGES_REQUESTED]: {
    reason: FOLLOWUP_REASON.CHANGES_REQUESTED,
    sourceType: FOLLOWUP_SOURCE.WORKFLOW,
    priority: FOLLOWUP_PRIORITY.HIGH,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.CHANGES_REQUESTED],
  },
  [FOLLOWUP_REASON.EXPIRING]: {
    reason: FOLLOWUP_REASON.EXPIRING,
    sourceType: FOLLOWUP_SOURCE.EXPIRY,
    priority: FOLLOWUP_PRIORITY.HIGH,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.EXPIRING],
  },
  [FOLLOWUP_REASON.ACCEPTED_NEXT_STEP]: {
    reason: FOLLOWUP_REASON.ACCEPTED_NEXT_STEP,
    sourceType: FOLLOWUP_SOURCE.PROPOSAL,
    priority: FOLLOWUP_PRIORITY.MEDIUM,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.ACCEPTED_NEXT_STEP],
  },
  [FOLLOWUP_REASON.OVERDUE_TASK]: {
    reason: FOLLOWUP_REASON.OVERDUE_TASK,
    sourceType: FOLLOWUP_SOURCE.WORKFLOW,
    priority: FOLLOWUP_PRIORITY.HIGH,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.OVERDUE_TASK],
  },
  [FOLLOWUP_REASON.MANUAL]: {
    reason: FOLLOWUP_REASON.MANUAL,
    sourceType: FOLLOWUP_SOURCE.MANUAL,
    priority: FOLLOWUP_PRIORITY.MEDIUM,
    title: FOLLOWUP_REASON_ACTIONS[FOLLOWUP_REASON.MANUAL],
  },
})

export function getFollowupReasonMeta(reason) {
  return FOLLOWUP_REASON_META[reason] ?? FOLLOWUP_REASON_META[FOLLOWUP_REASON.MANUAL]
}

export function followupSignalKey(reason, sourceId = '') {
  const scoped = String(sourceId ?? '').trim()
  return `${reason}:${scoped || '*'}`
}

export function reasonLabel(reason) {
  return FOLLOWUP_REASON_LABELS[reason] || String(reason || 'Follow-up')
}
