/**
 * H16.1–H16.14 — Foundation + Intake + Rules + Action Intents + Outbound Webhooks
 * + CRM + Activity Timeline + Activity persistence + Activity authoring facade
 * + Activity entity registry + Native Activity intake + mailbox envelope
 * + calendar event envelope + studio principal contract.
 *
 * H16.7 adds a read-only activity timeline projection. It owns no store, writes
 * nothing, and exposes no mutation surface.
 * H16.8 Slice 8.5 wires null/postgres boot into capabilities.
 * H16.9 Slice 9.1 adds the studio write facade over the registered repository.
 * Slice 9.2 makes buildTimeline / listStudioTimeline async. Slice 9.3 adds
 * the native_activity TimelineSource. Slice 9.4 adds authoring HTTP. Slice 9.5
 * enables the activityAuthoring flag; runtime still requires durable health.
 * H16.12 Slice 12.1 adds a vendor-neutral inbound mailbox envelope. Slice 12.2
 * maps that envelope through createStudioActivity. It does not persist a
 * mailbox store, poll, authenticate, or register a TimelineSource.
 * H16.13 Slice 13.1 adds a vendor-neutral inbound calendar event envelope.
 * Slice 13.2 maps that envelope through createStudioActivity. It does not persist a
 * calendar store, poll, authenticate, or register a TimelineSource.
 * H16.14 Slice 14.1 adds a Studio Principal contract (id, kind, displayName,
 * companyId). Slice 14.2 binds studio HTTP actorId/companyId claims to that
 * principal. Query/body cannot impersonate a bound actor or cross tenants.
 * The current trusted source is the workflow actor catalog. It does not
 * replace the authoring fixture or add login, JWT, cookies, sessions, or OAuth.
 *
 * Outbound webhook sync execution is capability-gated; live HTTPS requires
 * OUTBOUND_WEBHOOK_NETWORK=1. CRM execution is synchronous and ships with an
 * in-process mock adapter only — no OAuth, vendor SDKs, or network.
 * Outbox, workers, and retry schedulers remain out of scope.
 * CommercialClose provider adapters remain exclusively under H15.6.
 */

export {
  INTEGRATION_KIND,
  INTEGRATION_KINDS,
  INTEGRATION_KIND_LABELS,
  INTEGRATION_STATUS,
  INTEGRATION_STATUSES,
  INTEGRATION_STATUS_LABELS,
  INTEGRATION_REJECTION_REASON,
  INTEGRATION_CAPABILITIES,
  DEFAULT_COMPANY_ID,
  INTEGRATION_ISOLATION_COMPANY_ID,
} from './types.js'

export {
  SECRET_REF_PATTERN,
  normalizeSecretRef,
  assertNoSecretValues,
  makeSecretRefs,
  makeIntegrationConfig,
  cloneIntegrationConfig,
  presentClientIntegrationConfig,
  presentStudioIntegrationConfig,
  serializeIntegrationConfig,
  integrationConfigHasSecretMaterial,
} from './schema.js'

export {
  configureIntegrationConfigStore,
  allIntegrationConfigs,
  replaceIntegrationConfigs,
  resetIntegrationConfigStore,
  assertIntegrationCompanyScope,
  evaluateIntegrationCompanyScope,
  listIntegrationConfigsForCompany,
  getIntegrationConfigForCompany,
  upsertIntegrationConfigForCompany,
  deleteIntegrationConfigForCompany,
} from './config.js'

export {
  NULL_INTEGRATION_ADAPTER_ID,
  NULL_INTEGRATION_ADAPTER_IDS,
  HTTP_OUTBOUND_WEBHOOK_ADAPTER_ID,
  makeIntegrationAdapterDescriptor,
  registerIntegrationAdapter,
  getIntegrationAdapter,
  listIntegrationAdapters,
  resetIntegrationAdapterRegistry,
  createNullDeliveryAdapter,
  createNullCrmAdapter,
  createNullCalendarAdapter,
  createNullMessagingAdapter,
  createNullOutboundWebhookAdapter,
  createHttpOutboundWebhookAdapter,
  registerNullIntegrationAdapters,
  resolveEnabledIntegrationAdapter,
} from './adapters/index.js'

export {
  refuseCommercialCloseMutation,
  refuseDecisionSnapshotMutation,
  refuseProposalContentMutation,
  rejectIntegrationBoundary,
} from './boundaries.js'

export {
  AUTOMATION_EVENT_SCHEMA_VERSION,
  AUTOMATION_SOURCE_DOMAIN,
  AUTOMATION_SOURCE_DOMAINS,
  AUTOMATION_INTAKE_SOURCE_DOMAINS,
  AUTOMATION_INTAKE_STATUS,
  AUTOMATION_INTAKE_STATUSES,
  AUTOMATION_INTAKE_REASON,
  AUTOMATION_CANONICAL_SOURCE,
  sanitizeAutomationPayload,
  makeAutomationEventSource,
  makeAutomationEventCorrelation,
  makeAutomationIdempotencyKey,
  makeAutomationEvent,
  cloneAutomationEvent,
  presentClientAutomationEvent,
  presentStudioAutomationEvent,
  makeAutomationIntakeReceipt,
  normalizeDomainEvent,
  configureAutomationIntakeStore,
  allAutomationEvents,
  allAutomationIntakeReceipts,
  replaceAutomationIntakeLedger,
  resetAutomationIntakeStore,
  serializeAutomationIntakeLedger,
  findAutomationIntakeReceipt,
  findAutomationEventById,
  getAutomationEventById,
  listAcceptedAutomationEventsForCompany,
  listAutomationIntakeReceiptsForCompany,
  recordAcceptedAutomationIntake,
  recordAutomationIntakeReceiptOnly,
  ingestAutomationEvent,
  normalizeDomainEventForIntake,
  setAutomationEventAcceptedListener,
  startAutomationEventIntake,
  stopAutomationEventIntake,
  isAutomationEventIntakeRunning,
  fanoutDomainEmission,
  fanoutFollowupEmission,
  fanoutWorkflowEmission,
  fanoutPortalEmission,
  fanoutInteractionEmission,
  fanoutActivityEmission,
} from './events/index.js'

export {
  AUTOMATION_RULE_SCHEMA_VERSION,
  AUTOMATION_RULE_ACTION_TYPE,
  AUTOMATION_RULE_ACTION_TYPES,
  AUTOMATION_RULE_CONDITION_OP,
  AUTOMATION_RULE_CONDITION_OPS,
  AUTOMATION_RULE_EVENT_PATHS,
  AUTOMATION_RULE_RUN_STATUS,
  AUTOMATION_RULE_RUN_STATUSES,
  AUTOMATION_RULE_FAILURE_REASON,
  AUTOMATION_RULE_LIMITS,
  isAllowedAutomationRuleEventPath,
  readAutomationEventPath,
  makeAutomationRule,
  cloneAutomationRule,
  nextAutomationRuleVersion,
  presentStudioAutomationRule,
  makeAutomationRuleExecutionKey,
  makeAutomationRuleRun,
  cloneAutomationRuleRun,
  presentStudioAutomationRuleRun,
  evaluateAutomationPredicate,
  evaluateAutomationConditions,
  resolveAutomationActionParam,
  executeAutomationAction,
  configureAutomationRulesStore,
  allAutomationRules,
  allAutomationRuleRuns,
  replaceAutomationRules,
  replaceAutomationRuleRuns,
  resetAutomationRulesStore,
  resetAutomationRuleRunsStore,
  serializeAutomationRules,
  serializeAutomationRuleRuns,
  findAutomationRuleById,
  findAutomationRuleRunByIdempotencyKey,
  getAutomationRuleForCompany,
  listAutomationRulesForCompany,
  listEnabledAutomationRulesForCompany,
  listAutomationRuleRunsForCompany,
  upsertAutomationRuleRecord,
  deleteAutomationRuleRecord,
  recordAutomationRuleRun,
  getAutomationRuleEvaluationDepth,
  isAutomationRuleEvaluationActive,
  evaluateAutomationRulesForEvent,
  onAutomationEventAccepted,
  listStudioAutomationRules,
  getStudioAutomationRule,
  upsertStudioAutomationRule,
  patchStudioAutomationRule,
  deleteStudioAutomationRule,
  listStudioAutomationRuleRuns,
} from './rules/index.js'

export {
  AUTOMATION_ACTION_INTENT_SCHEMA_VERSION,
  AUTOMATION_ACTION_INTENT_STATUS,
  AUTOMATION_ACTION_INTENT_STATUSES,
  AUTOMATION_ACTION_INTENT_LIMITS,
  AUTOMATION_ACTION_INTENT_CANCEL_REASON,
  makeAutomationActionIntentIdempotencyKey,
  makeAutomationActionIntent,
  cloneAutomationActionIntent,
  presentStudioAutomationActionIntent,
  configureAutomationActionIntentStore,
  allAutomationActionIntents,
  replaceAutomationActionIntents,
  resetAutomationActionIntentStore,
  serializeAutomationActionIntents,
  findAutomationActionIntentById,
  findAutomationActionIntentByIdempotencyKey,
  getAutomationActionIntentForCompany,
  listAutomationActionIntentsForCompany,
  recordAutomationActionIntent,
  cancelAutomationActionIntent,
  isDeferredEnqueueActionType,
  kindForDeferredEnqueueAction,
  recordDeferredAutomationActionIntent,
  listStudioAutomationActionIntents,
  getStudioAutomationActionIntent,
  cancelStudioAutomationActionIntent,
} from './intents/index.js'

export {
  OUTBOUND_WEBHOOK_SCHEMA_VERSION,
  OUTBOUND_WEBHOOK_ENVELOPE_TYPE,
  OUTBOUND_WEBHOOK_NETWORK_ENV,
  OUTBOUND_WEBHOOK_DESTINATION_STATUS,
  OUTBOUND_WEBHOOK_DESTINATION_STATUSES,
  OUTBOUND_WEBHOOK_OUTCOME_STATUS,
  OUTBOUND_WEBHOOK_OUTCOME_STATUSES,
  OUTBOUND_WEBHOOK_FAILURE_CODE,
  OUTBOUND_WEBHOOK_FAILURE_CODES,
  OUTBOUND_WEBHOOK_ALLOWED_HEADERS,
  OUTBOUND_WEBHOOK_BLOCKED_HEADERS,
  OUTBOUND_WEBHOOK_LIMITS,
  makeOutboundWebhookDestination,
  cloneOutboundWebhookDestination,
  presentStudioOutboundWebhookDestination,
  serializeOutboundWebhookDestination,
  makeOutboundWebhookDeliveryOutcome,
  cloneOutboundWebhookDeliveryOutcome,
  presentStudioOutboundWebhookDeliveryOutcome,
  sanitizeOutboundWebhookData,
  normalizeOutboundWebhookHeaders,
  configureOutboundWebhookDestinationStore,
  allOutboundWebhookDestinations,
  replaceOutboundWebhookDestinations,
  resetOutboundWebhookDestinationStore,
  serializeOutboundWebhookDestinations,
  listOutboundWebhookDestinationsForCompany,
  getOutboundWebhookDestinationForCompany,
  upsertOutboundWebhookDestinationForCompany,
  setOutboundWebhookDestinationEnabled,
  deleteOutboundWebhookDestinationForCompany,
  configureOutboundWebhookOutcomeStore,
  allOutboundWebhookOutcomes,
  replaceOutboundWebhookOutcomes,
  resetOutboundWebhookOutcomeStore,
  serializeOutboundWebhookOutcomes,
  findOutboundWebhookOutcomeByIntentId,
  listOutboundWebhookOutcomesForCompany,
  getOutboundWebhookOutcomeForCompany,
  recordOutboundWebhookOutcome,
  stableStringify,
  buildOutboundWebhookEnvelope,
  serializeOutboundWebhookEnvelope,
  setOutboundWebhookTestSecrets,
  clearOutboundWebhookTestSecrets,
  resolveOutboundWebhookSecretRef,
  signOutboundWebhookBody,
  buildOutboundWebhookSignatureHeaders,
  setOutboundWebhookDnsResolverForTests,
  expandOutboundWebhookIpv6,
  extractIpv4FromMappedIpv6,
  normalizeOutboundWebhookIp,
  isBlockedOutboundWebhookIp,
  validateOutboundWebhookUrl,
  setOutboundWebhookTransportForTests,
  clearOutboundWebhookTransportForTests,
  isOutboundWebhookNetworkEnabled,
  createFakeOutboundWebhookTransport,
  createLiveOutboundWebhookTransport,
  getOutboundWebhookTransport,
  truncateOutboundWebhookResponseBody,
  setOutboundWebhooksCapabilityOverrideForTests,
  executeOutboundWebhookForIntent,
  listStudioOutboundWebhookDestinations,
  getStudioOutboundWebhookDestination,
  upsertStudioOutboundWebhookDestination,
  patchStudioOutboundWebhookDestination,
  deleteStudioOutboundWebhookDestination,
  listStudioOutboundWebhookOutcomes,
  getStudioOutboundWebhookOutcome,
  executeStudioOutboundWebhook,
} from './webhooks/index.js'

export {
  CRM_SCHEMA_VERSION,
  CRM_PROVIDER_NETWORK_ENV,
  CRM_PROVIDER_ID,
  CRM_PROVIDER_IDS,
  CRM_CONNECTION_STATUS,
  CRM_CONNECTION_STATUSES,
  CRM_CONNECTION_CONFIG_KEYS,
  CRM_OPERATION,
  CRM_OPERATIONS,
  CRM_RECORD_TYPE,
  CRM_RECORD_TYPES,
  CRM_RECORD_TYPE_BY_OPERATION,
  CRM_RECORD_FIELDS,
  CRM_FORBIDDEN_RECORD_FIELDS,
  CRM_OUTCOME_STATUS,
  CRM_OUTCOME_STATUSES,
  CRM_FAILURE_CODE,
  CRM_FAILURE_CODES,
  CRM_LIMITS,
  normalizeCrmConnectionConfig,
  normalizeCrmCredentialRefs,
  makeCrmConnection,
  cloneCrmConnection,
  presentStudioCrmConnection,
  serializeCrmConnection,
  sanitizeCrmResult,
  makeCrmExecutionOutcome,
  cloneCrmExecutionOutcome,
  presentStudioCrmExecutionOutcome,
  configureCrmConnectionStore,
  allCrmConnections,
  replaceCrmConnections,
  resetCrmConnectionStore,
  serializeCrmConnections,
  listCrmConnectionsForCompany,
  getCrmConnectionForCompany,
  upsertCrmConnectionForCompany,
  setCrmConnectionEnabled,
  deleteCrmConnectionForCompany,
  collectCrmRecordInput,
  extractCrmRecord,
  makeCrmExternalKey,
  buildCrmMutation,
  registerCrmAdapter,
  getCrmAdapter,
  listCrmAdapters,
  clearCrmAdapterRegistry,
  normalizeCrmAdapterResult,
  registerBuiltInCrmAdapters,
  createNullCrmAdapter as createNullCrmProviderAdapter,
  createMockCrmAdapter,
  resetMockCrmRecords,
  setMockCrmFailureForTests,
  clearMockCrmFailureForTests,
  getMockCrmRecord,
  listMockCrmRecords,
  configureCrmOutcomeStore,
  allCrmOutcomes,
  replaceCrmOutcomes,
  resetCrmOutcomeStore,
  serializeCrmOutcomes,
  findCrmOutcomeByIntentId,
  listCrmOutcomesForCompany,
  getCrmOutcomeForCompany,
  recordCrmOutcome,
  CRM_INTENT_ACTION_TYPE,
  setCrmCapabilityOverrideForTests,
  isCrmCapabilityEnabled,
  executeCrmIntent,
  listStudioCrmConnections,
  getStudioCrmConnection,
  upsertStudioCrmConnection,
  patchStudioCrmConnection,
  deleteStudioCrmConnection,
  listStudioCrmOutcomes,
  getStudioCrmOutcome,
  executeStudioCrmIntent,
} from './crm/index.js'

export {
  ACTIVITY_SCHEMA_VERSION,
  ACTIVITY_KIND,
  ACTIVITY_KINDS,
  ACTIVITY_PROJECTED_KINDS,
  ACTIVITY_ORIGIN,
  ACTIVITY_ORIGINS,
  ACTIVITY_PROJECTED_ORIGINS,
  ACTIVITY_AUDIENCE as ACTIVITY_TIMELINE_AUDIENCE,
  ACTIVITY_AUDIENCES as ACTIVITY_TIMELINE_AUDIENCES,
  ACTIVITY_ACTOR_KIND,
  ACTIVITY_ACTOR_KINDS,
  ACTIVITY_SUBJECT_TYPE,
  ACTIVITY_SUBJECT_TYPES,
  ACTIVITY_RESOLVABLE_SUBJECT_TYPES,
  TIMELINE_ENTRY_ID_PREFIX,
  TIMELINE_SOURCE_ID,
  TIMELINE_SOURCE_IDS,
  TIMELINE_SOURCE_PRIORITY,
  TIMELINE_UNSCOPED_SOURCE_IDS,
  TIMELINE_LIVING_CANONICAL_INTERACTION_TYPES,
  TIMELINE_DROP_REASON,
  TIMELINE_DROP_REASONS,
  TIMELINE_LIMITS,
  TIMELINE_CACHE_ID,
  TIMELINE_CACHE_MODE,
  TIMELINE_CACHE_MODES,
  TIMELINE_CACHE_LIMITS,
  assertTimelineSourceContract,
  registerTimelineSource,
  unregisterTimelineSource,
  resetTimelineSources,
  listRegisteredTimelineSources,
  getTimelineSource,
  describeTimelineSources,
  createAutomationLedgerTimelineSource,
  createLivingEventsTimelineSource,
  createDomainActivityTimelineSource,
  createWorkflowActivityTimelineSource,
  createPortalActivityTimelineSource,
  createInteractionActivityTimelineSource,
  createStudioAuditTimelineSource,
  createProposalActivityTimelineSource,
  createCommercialCloseHistoryTimelineSource,
  createNativeActivityTimelineSource,
  dedupeTimelineEntries,
  assertTimelineCacheContract,
  createNullTimelineCache,
  deriveTimelineCacheKey,
  deriveTimelineSourceFingerprint,
  describeTimelineCache,
  getTimelineCache,
  isTimelineCacheEnabled,
  isTimelinePageCacheable,
  registerTimelineCache,
  resetTimelineCache,
  resolveTimelineCacheTtlSeconds,
  projectTimelineCandidates,
  filterTimelineAudience,
  setActivityTimelineCapabilityOverrideForTests,
  clearActivityTimelineCapabilityOverrideForTests,
  setActivityAuthoringCapabilityOverrideForTests,
  clearActivityAuthoringCapabilityOverrideForTests,
  configureTimelineProposalLookup,
  resetTimelineProposalLookup,
  isActivityTimelineEnabled,
  isActivityAuthoringEnabled,
  assertProposalAccess,
  describeActivityRepository,
  isDurableActivityRepositoryHealthy,
  getActivityRepositoryHealth,
  refreshActivityRepositoryHealth,
  compareTimelineEntries,
  encodeTimelineCursor,
  decodeTimelineCursor,
  buildTimeline,
  listStudioTimeline,
  listStudioTimelineForProposal,
  describeStudioTimelineSources,
  getActivityCapabilities,
  STUDIO_ACTIVITY_AUTHORING_ACTOR,
  createStudioActivity,
  getStudioActivity,
  updateStudioActivity,
  archiveStudioActivity,
  emitNativeActivityCreated,
  deriveTimelineEntryId,
  sanitizeTimelineAttributes,
  resolveTimelineTimestamps,
  makeTimelineSubject,
  makeTimelineSource,
  makeTimelineActor,
  makeTimelineEntry,
  cloneTimelineEntry,
  presentStudioTimelineEntry,
  presentClientTimelineEntry,
} from './activities/index.js'

export {
  ACTIVITY_REPOSITORY_ID,
  ACTIVITY_REPOSITORY_IDS,
  ACTIVITY_REPOSITORY_MODE,
  ACTIVITY_REPOSITORY_MODES,
  ACTIVITY_NATIVE_ID_PREFIX,
  ACTIVITY_DATABASE_URL_ENV,
  ACTIVITY_NATIVE_KIND,
  ACTIVITY_NATIVE_KINDS,
  ACTIVITY_NATIVE_ORIGIN,
  ACTIVITY_NATIVE_ORIGINS,
  ACTIVITY_NATIVE_TYPE,
  ACTIVITY_NATIVE_TYPES,
  ACTIVITY_NATIVE_TYPE_BY_KIND,
  NATIVE_ACTIVITY_SCHEMA_VERSION,
  NATIVE_ACTIVITY_LIMITS,
  makeNativeActivity,
  cloneNativeActivity,
  assertActivityRepositoryContract,
  registerActivityRepository,
  getActivityRepository,
  resetActivityRepository,
  ensureActivityPersistence,
  createNullActivityRepository,
  createMemoryActivityRepository,
  resetMemoryActivityRepository,
  createPostgresActivityRepository,
  resetPostgresActivityRepository,
  assertActivityRepositoryConformance,
} from '../persistence/activities/index.js'

export {
  ACTIVITY_ENTITY_SCHEMA_VERSION,
  ACTIVITY_ENTITY_KIND,
  ACTIVITY_ENTITY_KINDS,
  ACTIVITY_ENTITY_LIMITS,
  ACTIVITY_ENTITY_NOT_FOUND,
  ACTIVITY_ENTITY_FORBIDDEN,
  ACTIVITY_ENTITY_FORBIDDEN_FIELDS,
  makeActivityEntity,
  cloneActivityEntity,
  resetActivityEntityStore,
  allActivityEntities,
  upsertActivityEntity,
  getActivityEntity,
  listActivityEntities,
  resolveActivityEntity,
  assertActivityEntityAccess,
} from './entities/index.js'

export {
  MAILBOX_SCHEMA_VERSION,
  MAILBOX_SOURCE_ID,
  MAILBOX_SOURCE_DOMAIN,
  MAILBOX_SOURCE_ENTITY_TYPE,
  MAILBOX_ACTIVITY_KIND,
  MAILBOX_ACTIVITY_TYPE,
  MAILBOX_DIRECTION,
  MAILBOX_DIRECTIONS,
  MAILBOX_RECIPIENT_ROLE,
  MAILBOX_RECIPIENT_ROLES,
  MAILBOX_CONTENT_MEDIA_TYPE,
  MAILBOX_CONTENT_MEDIA_TYPES,
  MAILBOX_LIMITS,
  MAILBOX_FORBIDDEN_FIELDS,
  MAILBOX_FORBIDDEN_CONTENT_FIELDS,
  MAILBOX_INGEST_STATUS,
  MAILBOX_INGEST_STATUSES,
  makeMailboxIdempotencyKey,
  makeInboundMailboxMessage,
  cloneInboundMailboxMessage,
  isMailboxSubjectSupplied,
  makeNativeMailboxIdempotencyKey,
  mapMailboxMessageToStudioActivityInput,
  ingestInboundMailboxMessage,
} from './mailbox/index.js'

export {
  CALENDAR_SCHEMA_VERSION,
  CALENDAR_SOURCE_ID,
  CALENDAR_SOURCE_DOMAIN,
  CALENDAR_SOURCE_ENTITY_TYPE,
  CALENDAR_ACTIVITY_KIND,
  CALENDAR_ACTIVITY_TYPE,
  CALENDAR_CONTENT_MEDIA_TYPE,
  CALENDAR_CONTENT_MEDIA_TYPES,
  CALENDAR_LIMITS,
  CALENDAR_FORBIDDEN_FIELDS,
  CALENDAR_FORBIDDEN_CONTENT_FIELDS,
  CALENDAR_INGEST_STATUS,
  CALENDAR_INGEST_STATUSES,
  makeCalendarIdempotencyKey,
  makeInboundCalendarEvent,
  cloneInboundCalendarEvent,
  isCalendarSubjectSupplied,
  makeNativeCalendarIdempotencyKey,
  mapCalendarEventToStudioActivityInput,
  ingestInboundCalendarEvent,
} from './calendar/index.js'

export {
  STUDIO_PRINCIPAL_SCHEMA_VERSION,
  STUDIO_PRINCIPAL_KIND,
  STUDIO_PRINCIPAL_KINDS,
  STUDIO_PRINCIPAL_LIMITS,
  STUDIO_PRINCIPAL_FORBIDDEN_FIELDS,
  makeStudioPrincipal,
  cloneStudioPrincipal,
  readClaimedStudioIdentity,
  getRequestStudioPrincipal,
  setRequestStudioPrincipal,
  bindStudioPrincipal,
  resolveStudioCatalogPrincipal,
  bindStudioRequest,
  studioRequestIdentity,
} from './identity/index.js'
