import { WORKFLOW_EVENT } from './types.js'

/**
 * Future systems subscribe to these names. Horizon 10 does not deliver them.
 */
export const WORKFLOW_NOTIFICATION_EVENTS = Object.freeze([
  WORKFLOW_EVENT.STATUS_CHANGED,
  WORKFLOW_EVENT.REVIEW_REQUESTED,
  WORKFLOW_EVENT.CHANGES_REQUESTED,
  WORKFLOW_EVENT.RESUBMITTED,
  WORKFLOW_EVENT.APPROVED,
  WORKFLOW_EVENT.READY_TO_SEND,
  WORKFLOW_EVENT.SENT,
  WORKFLOW_EVENT.VIEWED,
  WORKFLOW_EVENT.ACCEPTED,
  WORKFLOW_EVENT.REJECTED,
  WORKFLOW_EVENT.EXPIRED,
  WORKFLOW_EVENT.COMMENT_ADDED,
  WORKFLOW_EVENT.TASK_CREATED,
  WORKFLOW_EVENT.TASK_ASSIGNED,
  WORKFLOW_EVENT.TASK_COMPLETED,
  WORKFLOW_EVENT.APPROVAL_REQUESTED,
])

export function emitWorkflowEvent(_event) {
  return null
}
