import { CONTENT_BLOCK_TYPE } from '../models/contentBlock.js'

/**
 * Built-in Block Engine types for Proposal Experience v1.
 *
 * Layout Engine slot ids remain separate. These ids are stored on proposal
 * block instances and shared by screen, PDF and editor.
 */
export const BLOCK_TYPE = Object.freeze({
  COVER: CONTENT_BLOCK_TYPE.COVER,
  EXECUTIVE_SUMMARY: CONTENT_BLOCK_TYPE.EXECUTIVE_SUMMARY,
  RICH_TEXT: CONTENT_BLOCK_TYPE.RICH_TEXT,
  GALLERY: CONTENT_BLOCK_TYPE.GALLERY,
  PRICING: CONTENT_BLOCK_TYPE.PRICING,
  TIMELINE: CONTENT_BLOCK_TYPE.TIMELINE,
  DELIVERABLES: CONTENT_BLOCK_TYPE.DELIVERABLES,
  SPECIFICATIONS: CONTENT_BLOCK_TYPE.SPECIFICATIONS,
  TEAM: CONTENT_BLOCK_TYPE.TEAM,
  TESTIMONIALS: CONTENT_BLOCK_TYPE.TESTIMONIALS,
  FAQ: CONTENT_BLOCK_TYPE.FAQ,
  TERMS: CONTENT_BLOCK_TYPE.TERMS,
  SIGNATURE: CONTENT_BLOCK_TYPE.SIGNATURE,
  ATTACHMENTS: CONTENT_BLOCK_TYPE.ATTACHMENTS,
  CUSTOM: CONTENT_BLOCK_TYPE.CUSTOM,
})

export const BUILTIN_BLOCK_TYPES = Object.freeze(Object.values(BLOCK_TYPE))
